---

- name: Remove root password access from SSH
  when: security.ssh_disable_root_access_with_password
  tags: security
  notify: Restart SSH
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin yes'
    replace: 'PermitRootLogin without-password'

- name: Configure the firewall for SSH access
  tags: security
  ufw:
    proto: tcp
    port: 22
    src: '{{ access.src }}'
    rule: '{{ access.rule | default("allow") }}'
    comment: '{{ access.comment | default("") }}'
    state: enabled
  with_items:
    - '{{ firewall.ssh }}'
  loop_control:
    loop_var: access
