# Standard policies
policies:
  system:
    password: 'length=16 chars=ascii_letters,digits'
    passphrase: 'length=40'

# LDAP configuration
ldap:
  hostname: 'ldap.{{ network.domain }}'
  organization:
    domain: '{{ network.domain }}'
    base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  users:
    dn: 'ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  groups:
    dn: 'ou=groups, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  manager:
    uid: manager
    dn: 'cn=manager account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  readonly:
    uid: readonly
    dn: 'cn=readonly account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  admin:
    dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    desc: administrator account
  postmaster:
    uid: postmaster
    dn: 'cn=postmaster account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    # See https://www.ietf.org/rfc/rfc2142.txt
    mailAliases:
      - 'abuse@{{ network.domain }}'
      - 'noc@{{ network.domain }}'
      - 'security@{{ network.domain }}'
      - 'mailer-daemon@{{ network.domain }}'
      - 'webmaster@{{ network.domain }}'
      - 'hostmaster@{{ network.domain }}'
      - 'admin@{{ network.domain }}'
      - 'root@{{ network.domain }}'

  # password params
  roPasswdParams: "{{ playbook_dir }}/../../backup/ldap/readonly.pwd {{ policies.system.password }}"
  managerPasswdParams: "{{ playbook_dir }}/../../backup/ldap/manager.pwd {{ policies.system.password }}"
  adminPasswdParams: "{{ playbook_dir }}/../../backup/ldap/admin.pwd {{ policies.system.password }}"
  postmasterPasswdParams: "{{ playbook_dir }}/../../backup/ldap/postmaster.pwd {{ policies.system.password }}"


# Encryption parameters
encryption:
  systemKeyParams: "{{ playbook_dir }}/../../backup/encryption/system-key.pwd {{ policies.system.passphrase }}"
  backupKeyParams: "{{ playbook_dir }}/../../backup/encryption/backup-key.pwd {{ policies.system.passphrase }}"

###############################################################################
# Email related default options
mail_default:
  max_attachment_size: 25   # In megabytes
  autoconfig: true          # Support Thunderbird automatic configuration
  autodiscover: false       # Support MS Outlook automatic configuration (uses https)
  quota:
    default: 1G             # Maximum allowed mailbox size for your users.
                            # The safe maximum value will be automatically computed in a next version.
  discard_duplicates: true  # Discard duplicates messages. It is safe, but you can disable if you are worried
                            # The default timerange is 1h
  antivirus:                # Check inbound and outbound emails for viruses
    active: true            # or false
    action: drop            # Action to do when a virus is found in an email: bounce or drop
                            # be careful, bouncing external emails is a way to expose clamav usage
    send_warnings: false    # Send a warning email to - internal - users who are sending viruses
    quarantine: yes         # Place emails with a virus in quarantine, for further analysis
  impersonate:              # Activate dovecot "master" user feature, ideal for families and communities
    active: false           # https://wiki2.dovecot.org/Authentication/MasterUsers
    master: master          # master user name
    separator: '*'          # Separation char between master user / real user name. I personally use '/'
  #############################################################################
  import:                   # If you have users with "import" email active scripts, set this flag to true
    username: import        # The name of the user that import emails
    active: false           # A master user, with reduced rights will be created, to append miported emails
                            # in user's mailboxes.
  #############################################################################
  # Dovecot / solr FTS (Full Text search)
  fts:
    active: true
    langs:
      - id: fr
        name: French
      - id: en
        name: English
  #############################################################################
  advanced_features: false  # Use some advanced features that will need the latest version of dovecot
                            # from stretch-backports, like those below.
                            # like sending emails to an international addresses (e.g. andré@homebox.space)
  recipient_delimiter: '+'  # The characters you want to use to split email address from mailbox, i.e.:
                            # when receiving a message to john+lists@example.com, it should go directly to
                            # the 'lists' folder... I personally use '~'
