# LDAP configuration
ldap:
  hostname: 'ldap.{{ network.domain }}'
  organization:
    domain: '{{ network.domain }}'
    base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  users:
    dn: 'ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  groups:
    dn: 'ou=groups,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  manager:
    uid: manager
    dn: 'cn=manager account,ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  readonly:
    uid: readonly
    dn: 'cn=readonly account,ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  admin:
    dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    desc: administrator account
  # password params
  roPasswdParams: "{{ playbook_dir }}/../../backup/ldap/readonly.pwd length=16 chars=ascii_letters,digits"
  managerPasswdParams: "{{ playbook_dir }}/../../backup/ldap/manager.pwd length=16 chars=ascii_letters,digits"
  adminPasswdParams: "{{ playbook_dir }}/../../backup/ldap/admin.pwd length=16 chars=ascii_letters,digits"
