---

- name: Install dovecot packages
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-managesieved
    - dovecot-sieve
  loop_control:
        loop_var: pkg
    
