---

- name: Install opendkim packages for mail signing
  tags: dkim
  notify: Restart opendkim
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - opendkim
    - opendkim-tools
  loop_control:
    loop_var: pkg
    
- name: Create directory to install the keys
  tags: dkim
  notify: Restart opendkim
  file:
    path: /etc/opendkim/keys
    state: directory
    owner: opendkim
    group: opendkim
    mode: 0700

- name: If the DKIM have been generated before, copy them on the remote server
  tags: dkim
  synchronize:
    src: '../../backup/dkim-keys/'
    dest: '/etc/opendkim/keys/'
    mode: push
    owner: no
    group: no
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--checksum'

- name: Run the command to create the keys
  tags: dkim
  notify: Restart opendkim
  register: keys
  command: >-
    opendkim-genkey
    --restrict
    -D /etc/opendkim/keys
    -d '{{ network.domain }}'
    -b '{{ dkim.key_size }}'
    -s '{{ dkim.selector }}'
    -n '{{ dkim.note }}'
  args:
    creates: '/etc/opendkim/keys/{{ dkim.selector }}.txt'

- name: Backup the dkim on your local machine
  tags: dkim
  synchronize:
    mode: pull
    src: '/etc/opendkim/keys/{{ item }}'
    dest: '../../backup/dkim-keys/{{ item }}'
    perms: yes
  with_items:
    - '{{ dkim.selector }}.txt'
    - '{{ dkim.selector }}.private'

- name: Set the default permissions
  tags: dkim
  notify: Restart opendkim
  file:
    path: '{{ path }}'
    mode: u=rw,g=r,o=
    owner: opendkim
    group: opendkim
  with_items:
    - '/etc/opendkim/keys/{{ dkim.selector }}.private'
    - '/etc/opendkim/keys/{{ dkim.selector }}.txt'
  loop_control:
    loop_var: path

- name: Create the configuration file
  tags: dkim
  notify: Restart opendkim
  template:
    src: opendkim.conf
    dest: /etc/opendkim.conf

- name: Update the default configuration file for the socket
  tags: dkim
  notify: Restart opendkim
  replace:
    path: /etc/default/opendkim
    regexp: '^SOCKET.*'
    replace: 'SOCKET="inet:{{ milter_dkim_port }}@localhost"'

- name: Create the keys and signing table
  tags: dkim
  notify: Restart opendkim
  template:
    src: '{{ file }}'
    dest: '/etc/opendkim/{{ file }}'
  with_items:
    - keytable
    - signingtable
    - trusted-hosts
  loop_control:
    loop_var: file

