---

- name: Install opendkim packages for mail signing
  tags: dkim
  notify: Restart opendkim
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - opendkim
    - opendkim-tools
  loop_control:
    loop_var: pkg
    
- name: If the DKIM have been generated before, copy them on the remote server
  tags: dkim
  synchronize:
    src: ../../../backup/dkim-keys/
    dest: /etc/postfix
    mode: push
    owner: no
    group: no
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--checksum'
      - '--exclude=readme.md'

- name: Create directory to install the keys
  tags: dkim
  notify: Restart opendkim
  file:
    path: /etc/postfix/dkim/
    state: directory
    group: opendkim
    mode: u=rwx,g=rx,o=

- name: Run the command to create the keys
  tags: dkim
  notify: Restart opendkim
  register: keys
  command: >-
    opendkim-genkey
    -D /etc/postfix/dkim/
    -d '{{ network.domain }}'
    -b '{{ dkim.key_size }}'
    -s '{{ dkim.selector }}'
    -n '{{ dkim.note }}'
  args:
    creates: '/etc/postfix/dkim/{{ dkim.selector }}.txt'

- name: Backup the dkim on your local machine
  tags: dkim
  synchronize:
    mode: pull
    src: /etc/postfix/dkim
    dest: ../../../backup/dkim-keys/
    perms: yes

- name: Set the default permissions
  tags: dkim
  notify: Restart opendkim
  file:
    path: '{{ path }}'
    mode: u=rw,g=r,o=
    group: opendkim
  with_items:
    - '/etc/postfix/dkim/{{ dkim.selector }}.private'
    - '/etc/postfix/dkim/{{ dkim.selector }}.txt'
  loop_control:
    loop_var: path

- name: Update the configuration file
  tags: dkim
  notify: Restart opendkim
  lineinfile:
    path: /etc/opendkim.conf
    line: '{{ line }}'
    state: present
  with_items:
    - 'KeyTable file:/etc/postfix/dkim/keytable'
    - 'SigningTable file:/etc/postfix/dkim/signingtable'
    - 'Socket inet:{{ dkim.milter.port }}@localhost'
  loop_control:
    loop_var: line

- name: Update the configuration file for the socket
  tags: dkim
  notify: Restart opendkim
  lineinfile:
    path: /etc/default/opendkim
    line: '{{ line }}'
    state: present
  with_items:
    - 'SOCKET="inet:{{ dkim.milter.port }}@localhost"'
  loop_control:
    loop_var: line

- name: Create the keys and signing table
  tags: dkim
  notify: Restart opendkim
  template:
    src: '{{ file }}'
    dest: '/etc/postfix/dkim/{{ file }}'
  with_items:
    - keytable
    - signingtable
  loop_control:
    loop_var: file


