---

- name: Create the autoconfiguration directories
  tags: autoconfig
  file:
    path: '{{ path }}'
    state: directory
  with_items:
    - /var/www/autoconfig/mail/
    - /var/www/autodiscover/autodiscover/
  loop_control:
    loop_var: path

- name: Copy autoconfig XML template
  tags: autoconfig
  template:
    src: '{{ path.src }}'
    dest: '{{ path.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - src: config-v1.1.xml
      dest: /var/www/autoconfig/mail/config-v1.1.xml
    - src: autodiscover.xml
      dest: /var/www/autodiscover/autodiscover/autodiscover.xml
  loop_control:
    loop_var: path

- name: Create the autoconfig / autodiscover sites
  tags: autoconfig
  notify: Restart nginx server
  template:
    src: '{{ site }}.conf'
    dest: '/etc/nginx/sites-available/{{ site }}.conf'
    owner: root
    group: root
    mode: 0644
  with_items:
    - autoconfig
    - autodiscover
  loop_control:
    loop_var: site

- name: Enable nginx site
  tags: autoconfig
  file:
    src: '/etc/nginx/sites-available/{{ site }}.conf'
    dest: '/etc/nginx/sites-enabled/{{ site }}.conf'
    state: link
  with_items:
    - autoconfig
    - autodiscover
  loop_control:
    loop_var: site

# AppArmor configuration ======================================================

- name: Install nginx AppArmor profile
  when: security.app_armor
  tags: autoconfig, security, apparmor
  template:
    src: 'apparmor.d/local/autoconfig'
    dest: '/etc/apparmor.d/local/autoconfig'

- name: Add autoconfig AppAromor specific configuration
  when: security.app_armor
  tags: autoconfig, security, apparmor
  register: aa_config
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/autoconfig>'
    insertbefore: '# End of local includes for homebox'

- name: Activate AppArmor profiles
  when: security.app_armor and aa_config.changed
  tags: autoconfig, security, apparmor
  command: 'aa-enforce usr.sbin.nginx'
  notify: Restart AppArmor service

