
################################################################################
# Merge user options with default options
- name: Use default mail settings
  when: mail is not defined
  set_fact:
    mail: '{{ mail_default }}'

- name: Combine default and user defined mail settings
  when: mail is defined
  set_fact:
    mail: '{{ mail_default | combine(mail) }}'

- name: Display merged mail settings
  when: verbose is defined and verbose == True
  debug:
    var: mail

################################################################################
# Merge user options with default options
- name: Use default passwords settings
  when: passwords is not defined
  set_fact:
    passwords: '{{ passwords_default }}'

- name: Combine default and user defined password settings
  when: passwords is defined
  set_fact:
    passwords: '{{ passwords_default | combine(passwords) }}'

- name: Display merged password settings
  when: verbose is defined and verbose == True
  debug:
    var: passwords

################################################################################
# Merge system defaults
- name: Use default system settings
  when: system is not defined
  set_fact:
    system: '{{ system_default }}'

- name: Combine default and user defined system settings
  when: system is defined
  set_fact:
    system: '{{ system_default | combine(system) }}'

- name: Display merged system settings
  when: verbose is defined and verbose == True
  debug:
    var: system

################################################################################
# Merge firewall defaults
- name: Use default firewall settings
  when: firewall is not defined
  set_fact:
    firewall: '{{ firewall_default }}'

- name: Combine default and user defined firewall settings
  when: firewall is defined
  set_fact:
    firewall: '{{ firewall_default | combine(firewall) }}'

- name: Display merged firewall settings
  when: verbose is defined and verbose == True
  debug:
    var: firewall

################################################################################
# Merge security defaults
- name: Use default security settings
  when: security is not defined
  set_fact:
    security: '{{ security_default }}'

- name: Combine default and user defined security settings
  when: security is defined
  set_fact:
    security: '{{ security_default | combine(security) }}'

- name: Display merged security settings
  when: verbose is defined and verbose == True
  debug:
    var: security

################################################################################
# Merge dictionaries defaults
- name: Use default dictionaries settings
  when: dictionaries is not defined
  set_fact:
    dictionaries: '{{ dictionaries_default }}'

- name: Combine default and user defined dictionaries settings
  when: dictionaries is defined
  set_fact:
    dictionaries: '{{ dictionaries_default | union(dictionaries) }}'

- name: Display merged dictionaries settings
  when: verbose is defined and verbose == True
  debug:
    var: dictionaries

################################################################################
# Merge DNS defaults
- name: Use default DNS settings
  when: dns is not defined
  set_fact:
    dns: '{{ dns_default }}'

- name: Combine default and user defined dns settings
  when: dns is defined
  set_fact:
    dns: '{{ dns_default | combine(dns) }}'

- name: Display merged dns settings
  when: verbose is defined and verbose == True
  debug:
    var: dns

################################################################################
# Merge website defaults
- name: Use default website settings
  when: website is not defined
  set_fact:
    website: '{{ website_default }}'

- name: Combine default and user defined website settings
  when: website is defined
  set_fact:
    website: '{{ website_default | combine(website) }}'

- name: Display merged website settings
  when: verbose is defined and verbose == True
  debug:
    var: website
