---

- name: Get backup location
  tags: backup
  set_fact:
    protocol: '{{ location.url | regex_replace("://.*", "") }}'

- name: Get backup location components
  tags: backup
  register: location_user_facts
  shell: php -r 'echo parse_url("{{ location.url }}",  PHP_URL_USER);'

- name: Set the location user
  set_fact:
    location_user: '{{ location_user_facts.stdout | default("backup") }}'

- name: Get backup location components
  tags: backup
  register: location_host_facts
  shell: php -r 'echo parse_url("{{ location.url }}",  PHP_URL_HOST);'

- name: Set the location host
  set_fact:
    location_host: '{{ location_host_facts.stdout }}'

###############################################################################
- name: Check if it is a local directory for backup
  when: protocol == 'local'
  set_fact:
    path: '{{ location.url | regex_replace("local:/", "") }}'

- name: Create the local backup directory
  when: protocol == 'local'
  file:
    path:  '{{ path }}'
    state: directory
    mode: 0700
    owner: root
    group: root

###############################################################################
- name: Install the required file systems
  when: protocol == 'ssh'
  apt:
    name: 'sshfs'
    state: latest

- name: Configure the backup location
  when: protocol == 'ssh'
  template:
    src: 'ssh-config'
    dest: '/root/.ssh/config.d/backup-{{ location.name }}'

- name: Create the global ssh config for root
  assemble:
    src: /root/.ssh/config.d
    dest: /root/.ssh/config
    delimiter: "#---\n"
    mode: '0600'

###############################################################################
# Install FTP fuse fs if needed
- name: Install the required file systems
  when: protocol == 'ftp'
  apt:
    name: 'curlftpfs'
    state: latest

###############################################################################
# For Samba drives, uses cifs-utils
- name: Install the required file systems
  when: protocol == 'smb'
  apt:
    name: 'cifs-utils'
    state: latest

###############################################################################
# For usb drives, we will use autofs feature
- name: Install the required file systems
  when: protocol == 'usb'
  apt:
    name: 'autofs'
    state: latest

###############################################################################
- name: Install the required file systems
  when: protocol == 's3'
  apt:
    name: 's3fs'
    state: latest
