---

- name: Install required packages package
  tags: backup
  apt:
    name: '{{ pkg }}'
    state: latest
  with_items:
    - borgbackup
  loop_control:
    loop_var: pkg

- name: Create the backup mount point
  tags: backup
  file:
    path: /mnt/backup
    state: directory

- name: Configure each protocol
  include_tasks: install-protocol.yml
  with_items:
    - '{{ backup.locations }}'
  loop_control:
    loop_var: location
