---

- name: Create the DNS config into /etc/homebox
  tags: dns,gandi
  ini_file:
    path: '/etc/homebox/{{ network.domain }}.ini'
    section: main
    option: provider
    value: gandi
    mode: 0600

- name: Add the keys into the DNS config
  tags: dns,gandi
  ini_file:
    path: '/etc/homebox/{{ network.domain }}.ini'
    section: gandi
    option: key
    value: '{{ dns.gandi.key }}'

- name: Add the domain into the DNS config
  tags: dns,gandi
  ini_file:
    path: '/etc/homebox/{{ network.domain }}.ini'
    section: main
    option: domain
    value: '{{ network.domain }}'

- name: Copy the dns management script
  tags: dns,gandi
  copy:
    src: dns-gandi.py
    dest: /usr/local/sbin/dns-gandi
    mode: 0700
  
- name: Run the the dns management script
  tags: dns,gandi
  shell: >-
    /usr/local/sbin/dns-gandi
    --config /etc/homebox/{{ network.domain }}.ini
    --dkim-public-key-file /etc/postfix/dkim/{{ dkim.selector }}.txt
    --log-file /var/log/dns-update-gandi.log
    --log-level DEBUG
