site_name: homebox
pages:
  - Home: index.md
  - Installation: installation.md
  - Debian preseed: preseed.md
  - External accounts: external-accounts.md
  - Backup your emails: backup.md
  - Backup your deployment: deployment-backup.md
  - Testing and development: development.md
  - Code of conduct: codeofconduct.md
theme: readthedocs
