site_name: homebox
pages:
  - Home: index.md
  - Features: features.md
  - Installation: installation.md
  - Debian preseed: preseed.md
  - Main configuration file: configuration.md
  - Email configuration: email-configuration.md
  - External accounts: external-accounts.md
  - Backup your emails: backup.md
  - Backup your deployment: deployment-backup.md
  - Maintenance: maintenance.md
  - Testing and development: development.md
  - Code of conduct: codeofconduct.md
theme: readthedocs
#theme: mkdocs
