---

# This is checking that the DNS server has been fully propagated
- name: Check DNS propagation
  shell: >-
    host main.{{ network.domain }}

# This is checking that the DNS server has been fully propagated
- name: Check DNS propagation for backup IP address
  when: network.backup_ip is defined
  shell: >-
    host backup.{{ network.domain }}
