---

- name: Create the group home folders if necessary
  tags: accounts
  file:
    path: '/home/{{ user.group }}'
    owner: root
    group: '{{ user.group }}'
    state: directory
  with_items:
    - '{{ users }}'
  loop_control:
    loop_var: user

- name: Create the user account home folders
  tags: accounts
  file:
    path: '/home/{{ user.group }}/{{ user.uid }}'
    owner: '{{ user.uid }}'
    group: '{{ user.group }}'
    state: directory
    mode: 0700
    recurse: true
  with_items:
    - '{{ users }}'
  loop_control:
    loop_var: user

- name: Create the user account mail folders
  tags: accounts
  file:
    path: '/home/{{ user.group }}/{{ user.uid }}/mails/maildir'
    owner: '{{ user.uid }}'
    group: '{{ user.group }}'
    state: directory
    mode: 0700
    recurse: true
  with_items:
    - '{{ users }}'
  loop_control:
    loop_var: user

- name: Create home directory for users on first login
  tags: ldap
  when: system.login == true
  lineinfile:
    dest: /etc/pam.d/common-account
    line: 'session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0022'


