---

# Install postfix packages
- name: Install postfix packages
  tags: postfix
  notify: Restart postfix
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - postfix
    - postfix-cdb
    - postfix-pcre
    - postfix-ldap
    - sasl2-bin
    - postfix-policyd-spf-python
  loop_control:
    loop_var: pkg

################################################################################
# At this point, the certificates should have been created already #############
# in order to have SSL and TLS encryption activated.                           #
- name: Allow postfix to access the certificate directories
  tags: postfix,ssl
  notify: Restart postfix
  when: system.ssl == 'letsencrypt'
  vars:
    details:
      - [ /etc/letsencrypt/archive, /etc/letsencrypt/live ]
      - [ postfix ]
  acl:
    path: '{{ item[0] }}'
    entity: '{{ item[1] }}'
    etype: user
    permissions: rx
    state: present
  with_nested: '{{ details }}'

#                                                                              #
# End of TLS / SSL Configuration ###############################################

- name: Ensure the imap server FQDN resolves to localhost
  tags: postfix
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1    smtp.{{ network.domain }}'
    
- name: Install postfix packages for local administration
  tags: postfix
  notify: Restart postfix
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - pfqueue
    - bsd-mailx
  loop_control:
    loop_var: pkg

# The typical base64 overhead is 33%, and the value in the configuration file is in Mb
# So the value is max_attachment_size * 1.33 * 1024 * 1024, i.e. max_attachment_size * 1394606
# Adding 1Kb for the message text, because we are generous (sic)
- name: Compute max message size from max attachment size
  tags: postfix
  set_fact:
    message_size_limit: '{{ 1024 + mail.max_attachment_size * 1394606 | int }}'

- name: Copy configuration template
  tags: postfix
  notify: Restart postfix
  template:
    src: "{{ file }}"
    dest: "/etc/postfix/{{ file }}"
  with_items:
    - master.cf
    - main.cf
    - ldap-aliases.cf
  loop_control:
    loop_var: file

- name: Configure the firewall for default access
  tags: postfix,security
  ufw:
    rule: allow
    proto: tcp
    src: any
    port: '{{ rule.port }}'
    comment: '{{ rule.comment }}'
  with_items:
    - comment: Allow basic SMTP
      port: 25
    - comment: Allow encrypted SMTP
      port: 465
    - comment: Allow submission
      port: 587
  loop_control:
    loop_var: rule
