---

# Install postfix packages
- name: Install postfix packages
  tags: postfix
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - postfix
    - postfix-cdb
    - postfix-pcre
    - postfix-ldap
    - sasl2-bin
    - pfqueue
    - bsd-mailx
  loop_control:
    loop_var: pkg
    
- name: Copy configuration template
  tags: postfix
  register: config
  template:
    src: "{{ file }}"
    dest: "/etc/postfix/{{ file }}"
  with_items:
    - main.cf
    # - headers-check
    # - internal-domains
    # - internal-senders
    # - senders-bcc
    # - virtual
  loop_control:
    loop_var: file
    
- name: Restart postfix
  tags: postfix
  when: config.changed
  service:
    name: postfix
    state: restarted
  with_items:
    - postfix
    - postfix@-
  loop_control:
    loop_var: pkg
