---

- name: Update packages cache
  apt:
    update_cache: true
    
- name: install the required packages to build the ISO image
  apt:
    name: '{{ pkg }}'
    state: installed
  with_items:
    - simple-cdd
    - tar
    - xorriso
  loop_control:
    loop_var: pkg

- name: create the working directory in /tmp
  tags: preseed
  file:
    path: /tmp/homebox
    state: directory
  
- name: Copy the configuration file for simple cdd
  tags: preseed
  template:
    src: common.conf
    dest: /tmp/homebox/common.conf
  
- name: Copy the build script
  tags: preseed
  template:
    src: build.sh
    dest: /tmp/homebox/build.sh
    mode: 0744
  
- name: Create the profile folder
  tags: preseed
  file:
    path: /tmp/homebox/profiles
    state: directory
    
- name: Copy the profile folder content
  tags: preseed
  template:
    src: "profiles/{{ item }}"
    dest: "/tmp/homebox/profiles/{{ item }}"
  with_items:
    - default.description
    - default.packages
    - default.postinst

- name: Create the profile folder
  tags: preseed
  file:
    path: /tmp/homebox/profiles/preseed
    state: directory
    
- name: Copy the preseed files
  tags: preseed
  template:
    src: "{{ item }}"
    dest: "/tmp/homebox/profiles/preseed/{{ item | basename }}"
  with_fileglob:
    - ../templates/profiles/preseed/*.preseed

- name: Assemble the global preseed file
  assemble:
    src: "/tmp/homebox/profiles/preseed/"
    dest: "/tmp/homebox/profiles/default.preseed"
    

- name: Copy the files that need to be on the CD/DVD image
  tags: preseed
  copy:
    src: ../../../../misc
    dest: /tmp/homebox

# TODO: Dynamicall add the version number
- name: Copy the logo in the temporary folder for the installer
  copy:
    src: ../../logos/logo-small.png
    dest: /tmp/homebox/splash.png
  
# Run the script to create the iso images
- name: Run the command to create the iso file
  command: "./build.sh {{ system.hostname }}"
  args:
    chdir: /tmp/homebox
    creates: '/tmp/homebox/images/debian-{{ system.version }}-{{ system.arch }}-DVD-1.iso'
    
- name: Move the iso image to the appropriate folder
  copy:
    src: /tmp/homebox/images/debian-9.2-amd64-DVD-1.iso
    dest: "/var/lib/libvirt/images/{{ system.hostname }}-install.iso"
    remote_src: true

# Run the script to create the iso images
- name: Remove the file
  file:
    path: /tmp/homebox/images/debian-{{ system.version }}-{{ system.arch }}-DVD-1.iso
    state: absent
    
# Clean up
# - name: Clean up the working directory in /tmp
#   file:
#     path: /tmp/homebox
#     state: absent
  
