
- name: Restart nginx
  notify: Restart IMAP proxy
  service:
    name: nginx
    state: restarted

- name: Restart IMAP proxy
  service:
    name: imapproxy
    state: restarted

- name: Restart AppArmor service
  tags: dovecot
  service:
    name: apparmor
    state: restarted
