# User storage quotas for email
quota:
  per_user: '{{ mail.quota.default }}'
  listener:
    port: '{{ mails_quota_port }}'


sieve:
  global_scripts:
    - duplicate-checks.sieve
    - sent-checks.sieve
    - before-global.sieve
    - report-spam.sieve
    - report-ham.sieve
    - tags-important.sieve

# Default dovecot packages to install
dovecot:
  packages:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-managesieved
    - dovecot-sieve
    - dovecot-ldap
