---

- name: Configure the automatic security updates
  tags: security
  notify: Restart the automatic upgrades service
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Install fail2ban
  tags: security
  apt:
    name: fail2ban
    state: latest
  
