---

- name: Configure the automatic security updates
  register: unattended_upgrades
  tags: security
  template:
    src: 50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades

- name: Restart the automatic upgrades service if necessary
  when: unattended_upgrades.changed
  tags: security
  service:
    name: unattended-upgrades
    state: restarted

