---

# Limit SSH
- name: Configuring the firewall
  ufw:
    rule: limit
    port: ssh
    proto: tcp

# Allow some mail ports
- ufw:
    rule: allow
    port: '{{ item }}'
    proto: tcp
  with_items:
    - 80
    - 443
    - 25
    - 587
    - 143
    - 993
    - 110
    - 995

# Activate the firewall
- ufw:
    state: enabled
