---

version: '2'

services:
  homebox:
    build: homebox
    image: homebox:latest
    ports:
      - '22:22'
      - '80:80'
      - '443:443'
      - '143:143'
      - '993:993'
      - '25:25'
      - '587:587'
      - '465:465'
  client:
    build: client
    image: client:latest
    ports:
      - '22:22'
