---

# Install dovecot packages
- name: Install dovecot packages
  tags: dovecot
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-managesieved
    - dovecot-sieve
    - dovecot-ldap
  loop_control:
    loop_var: pkg

# Activate SSL on the imap server
- name: Activate SSL configuration
  tags: dovecot
  replace:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '{{ line.regexp }}'
    replace: '{{ line.replace }}'
  with_items:
    - '{{ config.ssl }}'
  loop_control:
    loop_var: line

- name: Activate LDAP configuration
  tags: dovecot
  replace:
    path: /etc/dovecot/dovecot-ldap.conf.ext
    regexp: '{{ line.regexp }}'
    replace: '{{ line.replace }}'
  with_items:
    - '{{ config.ldap }}'
  loop_control:
    loop_var: line

- name: Ensure the imap server FQDN resolves to localhost
  tags: dovecot
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1    {{ network.imap }}'
    
# - name: Create indexes and control directory
#   file:
#     path: "/var/vmail/{{ dir }}"
#     state: directory
#     owner: dovecot
#     group: users
#     mode: 0775
#   with_items:
#     - indexes
#     - control
#   loop_control:
#     loop_var: dir
    

# - name: Restart dovecot
#   when: config.changed
#   service:
#     name: dovecot
#     state: restarted
      
