---

# Install dovecot packages
- name: Install dovecot packages
  tags: dovecot
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-managesieved
    - dovecot-sieve
    - dovecot-ldap
  loop_control:
    loop_var: pkg

- name: Ensure the imap server FQDN resolves to localhost
  tags: dovecot
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1    {{ network.imap }}'

# Activate SSL on the imap server
- name: Activate SSL configuration
  tags: dovecot
  replace:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '{{ line.regexp }}'
    replace: '{{ line.replace }}'
  with_items:
   - regexp: '^#?ssl = no'
     replace: 'ssl = yes'
   - regexp: '#?ssl_cert =.*'
     replace: 'ssl_cert = </etc/letsencrypt/live/{{ certificate.cn }}/cert.pem'
   - regexp: '#?ssl_key =.*'
     replace: 'ssl_key = </etc/letsencrypt/live/{{ certificate.cn }}/privkey.pem'
   - regexp: '#?ssl_ca =.*'
     replace: 'ssl_ca = </etc/letsencrypt/live/{{ certificate.cn }}/fullchain.pem'
  loop_control:
    loop_var: line

- name: Activate LDAP configuration
  tags: dovecot
  replace:
    path: /etc/dovecot/dovecot-ldap.conf.ext
    regexp: '{{ line.regexp }}'
    replace: '{{ line.replace }}'
  with_items:
   - regexp: '^#?hosts =.*'
     replace: 'hosts = 127.0.0.1:389'
   - regexp: '^#?base =.*'
     replace: 'base = {{ ldap.organization.base }}'
   - regexp: '^#?scope = .*'
     replace: 'scope = subtree'
  loop_control:
    loop_var: line

- name: Activate dovecot authentication
  tags: dovecot
  template:
    src: 10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf      
