---

# Install dovecot packages
- name: Install dovecot packages
  tags: dovecot
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-lmtpd
    - dovecot-pop3d
    - dovecot-managesieved
    - dovecot-sieve
    - dovecot-ldap
  loop_control:
    loop_var: pkg

################################################################################
# At this point, the certificates should have been created already #############
# in order to have SSL and TLS encryption activated.                           #
- name: Allow slapd and nslcd daemons to access the certificate directories
  tags: ldap,ssl
  notify: Restart dovecot
  when: system.ssl == 'letsencrypt'
  vars:
    details:
      - [ /etc/letsencrypt/archive, /etc/letsencrypt/live ]
      - [ dovecot ]
  acl:
    path: '{{ item[0] }}'
    entity: '{{ item[1] }}'
    etype: user
    permissions: rx
    state: present
  with_nested: '{{ details }}'

#                                                                              #
# End of TLS / SSL Configuration ###############################################

- name: Ensure the imap server FQDN resolves to localhost
  tags: dovecot
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1    {{ network.imap }}'

# Activate SSL on the imap server
- name: Activate SSL configuration
  tags: dovecot
  notify: Restart dovecot
  when: system.ssl == 'letsencrypt'
  replace:
    path: /etc/dovecot/conf.d/10-ssl.conf
    regexp: '{{ line.regexp }}'
    replace: '{{ line.replace }}'
  with_items:
   - regexp: '^#?ssl = no'
     replace: 'ssl = yes'
   - regexp: '#?ssl_cert =.*'
     replace: 'ssl_cert = </etc/letsencrypt/live/{{ certificate.cn }}/cert.pem'
   - regexp: '#?ssl_key =.*'
     replace: 'ssl_key = </etc/letsencrypt/live/{{ certificate.cn }}/privkey.pem'
   - regexp: '#?ssl_ca =.*'
     replace: 'ssl_ca = </etc/letsencrypt/live/{{ certificate.cn }}/fullchain.pem'
  loop_control:
    loop_var: line

- name: Activate LDAP configuration
  tags: dovecot
  notify: Restart dovecot
  replace:
    path: /etc/dovecot/dovecot-ldap.conf.ext
    regexp: '{{ line.regexp }}'
    replace: '{{ line.replace }}'
  with_items:
   - regexp: '^#?hosts =.*'
     replace: 'hosts = 127.0.0.1:389'
   - regexp: '^#?base =.*'
     replace: 'base = {{ ldap.organization.base }}'
   - regexp: '^#?scope = .*'
     replace: 'scope = subtree'
  loop_control:
    loop_var: line

- name: Activate dovecot authentication
  tags: dovecot
  notify: Restart dovecot
  template:
    src: 10-master.conf
    dest: /etc/dovecot/conf.d/10-master.conf

