---

# Install dovecot packages
- name: Install dovecot packages
  tags: dovecot
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - '{{ dovecot.packages }}'
  loop_control:
    loop_var: pkg

################################################################################
# At this point, the certificates should have been created already #############
# in order to have SSL and TLS encryption activated.                           #
- name: Allow slapd and nslcd daemons to access the certificate directories
  tags: dovecot,ssl
  notify: Restart dovecot
  when: system.ssl == 'letsencrypt'
  vars:
    details:
      - [ /etc/letsencrypt/archive, /etc/letsencrypt/live ]
      - [ dovecot ]
  acl:
    path: '{{ item[0] }}'
    entity: '{{ item[1] }}'
    etype: user
    permissions: rx
    state: present
  with_nested: '{{ details }}'

#                                                                              #
# End of TLS / SSL Configuration ###############################################

- name: Ensure the imap server FQDN resolves to localhost
  tags: dovecot
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1    imap.{{ network.domain }}'

# Activate SSL on the imap server
- name: Activate SSL configuration
  tags: dovecot
  notify: Restart dovecot
  when: system.ssl == 'letsencrypt'
  template:
    src: 'conf.d/{{ file }}'
    dest: '/etc/dovecot/conf.d/{{ file }}'
  with_items:
    - 10-ssl.conf
  loop_control:
    loop_var: file

- name: Create dovecot global configuration files
  tags: dovecot
  notify: Restart dovecot
  template:
    src: '{{ file }}'
    dest: '/etc/dovecot/{{ file }}'
    mode: 0600
  with_items:
    - dovecot-ldap.conf.ext
  loop_control:
    loop_var: file

- name: Create dovecot conf.d configuration files
  tags: dovecot
  notify: Restart dovecot
  template:
    src: 'conf.d/{{ file }}'
    dest: '/etc/dovecot/conf.d/{{ file }}'
  with_items:
    - 10-auth.conf
    - 10-master.conf
    - 10-mail.conf
    - 10-logging.conf
    - 15-lda.conf
    - 15-mailboxes.conf
    - 20-managesieve.conf
    - 20-imap.conf
    - 20-lmtp.conf
    - 90-sieve.conf
    - 90-plugin.conf
    - 90-quota.conf
  loop_control:
    loop_var: file

- name: Create the global sieve directory
  tags: sieve
  file:
    path: /etc/dovecot/sieve
    state: directory

- name: Copy global sieve configuration
  tags: sieve
  notify: Restart dovecot
  template:
    src: 'sieve/{{ file.name }}'
    dest: '/etc/dovecot/sieve/{{ file.name }}'
    mode: '{{ file.mode | default(644) }}'
  with_items:
    - name: before-global.sieve
    - name: report-spam.sieve
    - name: report-ham.sieve
    - name: learn-spam.sh
      mode: 755
    - name: learn-ham.sh
      mode: 755
  loop_control:
    loop_var: file

- name: Configure the firewall for default access
  tags: security
  ufw:
    rule: allow
    proto: tcp
    src: any
    port: '{{ rule.port }}'
    comment: '{{ rule.comment }}'
  with_items:
    - comment: Allow IMAP access
      port: 143
    - comment: Allow IMAPS access
      port: 993
    - comment: Allow POP3 access
      port: 110
    - comment: Allow POP3S access
      port: 995
    - comment: Allow Managesieve access
      port: 4190
  loop_control:
    loop_var: rule

# AppArmor configuration ======================================================
- name: Install some dovecot AppArmor profile
  when: security.app_armor
  tags: dovecot, security, apparmor
  register: aa_templates
  template:
    src: 'apparmor.d/{{ aa_config }}'
    dest: '/etc/apparmor.d/{{ aa_config }}'
  with_items:
    - tunables/dovecot
    - local/usr.sbin.dovecot
    - local/usr.lib.dovecot.imap
    - local/usr.lib.dovecot.pop3
    - local/usr.lib.dovecot.lmtp
    - local/usr.lib.dovecot.config
    - local/usr.lib.dovecot.auth
    - local/usr.lib.dovecot.managesieve
    - local/usr.lib.dovecot.quota-status
    - usr.lib.dovecot.quota-status
  loop_control:
    loop_var: aa_config

- name: Activate AppArmor profiles
  when: security.app_armor and aa_templates.changed
  tags: dovecot, security, apparmor
  notify: Restart AppArmor service
  command: 'aa-enforce {{ aa_config }}'
  with_items:
    - usr.sbin.dovecot
    - usr.lib.dovecot.imap
    - usr.lib.dovecot.pop3
    - usr.lib.dovecot.lmtp
    - usr.lib.dovecot.config
    - usr.lib.dovecot.auth
    - usr.lib.dovecot.managesieve
    - usr.lib.dovecot.quota-status
    - usr.lib.dovecot.anvil
    - usr.lib.dovecot.deliver
    - usr.lib.dovecot.dict
    - usr.lib.dovecot.dovecot-auth
    - usr.lib.dovecot.dovecot-lda
    - usr.lib.dovecot.imap-login
    - usr.lib.dovecot.log
    - usr.lib.dovecot.managesieve-login
    - usr.lib.dovecot.pop3-login
    - usr.lib.dovecot.ssl-params
  loop_control:
    loop_var: aa_config

