---

- name: Create a directory for the zabbix passwords
  tags: backup
  delegate_to: localhost
  file:
    path: '{{ playbook_dir }}/../../backup/{{ network.domain }}/zabbix/'
    state: directory

- name: Set facts for zabbix password generation
  tags: password
  set_fact:
    password_path: "{{ playbook_dir }}/../../backup/{{ network.domain }}/zabbix/postgres.pwd"
    password_params: "length=16 chars=ascii_letters,digits"

- name: Generate a random password for zabbix
  tags: password
  set_fact:
    zabbixdb_password: '{{ lookup("password", "{{ password_path }} {{ password_params }}") }}'

- name: Install the required packages
  tags: apt
  apt:
    name: "{{ pkg }}"
    state: present
  with_items:
    - zabbix-server-pgsql
    - zabbix-agent
    - zabbix-frontend-php
    - python-psycopg2
    - postgresql-client
  loop_control:
    loop_var: pkg

- name: Install a simple nginx frontend
  template:
    src: webfrontend.conf.j2
    dest: '/etc/nginx/sites-available/zabbix.{{ network.domain }}.conf'

- name: Activate web frontend
  tags: roundcube
  notify:
    - Restart nginx
    - Restart php-fpm
  file:
    src: '/etc/nginx/sites-available/zabbix.{{ network.domain }}.conf'
    dest: '/etc/nginx/sites-enabled/zabbix.{{ network.domain }}.conf'
    state: link

# AppArmor configuration ======================================================

- name: Install nginx AppArmor profile
  when: security.app_armor
  notify:
    - Activate AppArmor profile
    - Restart AppArmor service
    - Restart nginx
  tags: zabbix, security, apparmor
  template:
    src: apparmor.d/local/zabbix
    dest: /etc/apparmor.d/local/zabbix

- name: Add zabbix AppArmor specific configuration
  when: security.app_armor
  notify:
    - Activate AppArmor profile
    - Restart AppArmor service
    - Restart nginx
  tags: zabbix, security, apparmor
  lineinfile:
    path: /etc/apparmor.d/usr.sbin.nginx
    line: '  #include <local/zabbix>'
    insertbefore: '# End of local includes for homebox'

- name: Get the current timezone
  register: timezone
  shell: cat /etc/timezone

- name: Update PHP configuration
  notify: Restart php-fpm
  replace:
    path: /etc/php/7.0/fpm/php.ini
    regexp: '{{ option.regexp }}'
    replace: '{{ option.replace }}'
  with_items:
    - regexp: '^max_execution_time\s=\s[0-9]+'
      replace: 'max_execution_time = 300'
    - regexp: '^max_input_time\s=\s[0-9]+'
      replace: 'max_imput_time = 300'
    - regexp: '^;?date.timezone\s=.*'
      replace: 'date.timezone = {{ timezone.stdout }}'
  loop_control:
    loop_var: option

- name: Create the database
  register: zabbixdb
  tags: postgres
  become: true
  become_user: postgres
  postgresql_db:
    encoding: utf8
    name: zabbix

- name: Create the database user
  tags: postgres
  become: true
  become_user: postgres
  postgresql_user:
    name: zabbix
    db: zabbix
    password: '{{ zabbixdb_password }}'
    role_attr_flags: LOGIN
    priv: ALL

- name: Initialise the database
  when: zabbixdb.changed
  tags: postgres
  become: true
  become_user: postgres
  shell: >-
    zcat /usr/share/zabbix-server-pgsql/{{ sql_file }}.sql.gz
    > /tmp/zabbix-{{ sql_file }}.sql &&
    psql -d zabbix -f /tmp/zabbix-{{ sql_file }}.sql
    -o /tmp/zabbix-{{ sql_file }}-install.log
  with_items:
    - schema
    - images
    - data
  loop_control:
    loop_var: sql_file

- name: Initialise grants
  tags: postgres
  become: true
  become_user: postgres
  postgresql_privs:
    type: database
    db: zabbix
    privs: ALL
    roles: zabbix

- name: Initialise Zabbix configuration
  tags: config
  replace:
    path: /etc/zabbix/zabbix_server.conf
    regexp: '^[#\s]*DBPassword\s?=.*'
    replace: 'DBPassword={{ zabbixdb_password }}'

# - name: Remove the python / psycopg2 package
#   tags: apt
#   apt:
#     name: python-psycopg2
#     state: absent
