
# The password is stored in cleartext in this file, and encrypted using Ansible password_hash
# Copy this file into accounts.yml to create your accounts

users:
  - name: andre
    full_name: "André Rodier"
    group: users
    shell: /bin/bash
    password: "vju5zPEGsB2L"
  - name: mirina
    full_name: "Mirina Rodier"
    group: users
    shell: /bin/bash
    password: "WKdTrtbpcqgq"
  - name: lucile
    full_name: "Lucile Rodier"
    group: users
    shell: /bin/bash
    password: "WKdTrtbpcqgq"
  - name: alexandra
    full_name: "Alexandra Rodier"
    group: users
    shell: /bin/bash
    password: "WKdTrtbpcqgq"

