# Common variables to the whole system

# System related
system:
  release: stretch

# Network related
network:
  smtp: smtp.example.com
  imap: imap.example.com
  hostname: mail.example.com
  domain: example.com

# Email related
mail:
  admin:
    name: "John Doe"
    email: admin@example.com
    user: "john"

# LDAP configuration
ldap:
  hostname: ldap.example.com
  organization:
    domain: example.com
    base: dc=example,dc=com
  users:
    dn: ou=users,dc=example,dc=com
  groups:
    dn: ou=groups,dc=example,dc=com
  manager:
    uid: manager
    password: homebox
  admin:
    dn: cn=admin,dc=example,dc=com
    desc: administrator account
    password: homebox

# Options
options:
  accounts:
    login: true
  local_admin: true


# Email related
mail:
  admin:
    name: "John Doe"
    email: jdoe@example.com
    user: jdoe

# For automatic DNS update
dns:
  gandi:
    handle: JD123-GANDI
    key: zaNGbUVIvi1KbYb6PPMdiQLh    # Your Gandi Key should be 24 characters long, e.g. zaNGbUVIvi1KbYb6PPMdiQLh
