# Common variables to the whole system

# Network related
network:
  smtp: smtp2.example.com
  imap: imap2.example.com
  hostname: mail2.example.com
  domain: example.com

# Email related
mail:
  admin:
    name: "John Doe"
    email: admin@example.com
    user: "john"

# LDAP configuration
ldap:
  organization:
    domain: example.com
    suffix: dc=example,dc=com
  users:
    dn: ou=users,dc=example,dc=com
  admin:
    dn: cn=admin,dc=example,dc=com
    desc: administrator account
    password: homebox
    

