---

# Webmail configuration
certificate:
  cn: webmail.homebox.space      # Will be used to create the URL
  email: admin@homebox.space     # The registered email address
  readby: www-data


webmail:
  url: '{{ certificate.cn }}'
  secure_port: 443
  title: 'Roundcube Webmail ({{ ldap.organization.domain }})'
  plugins:
    - password
    - archive
    - markasjunk
    - newmail_notifier
    - autologon
    - subscriptions_option
    - emoticons
    - new_user_identity
    # - new_user_dialog
    # - additional_message_headers
    # - managesieve
    # - acl
    # - database_attachments
    # - debug_logger
    # - enigma
    # - filesystem_attachments
    # - help
    # - hide_blockquote
    # - http_authentication
    # - jqueryui
    # - show_additional_headers
    # - squirrelmail_usercopy
    # - userinfo
    # - vcard_attachments
    # - virtuser_file
    # - virtuser_query
    # - zipdownload
