---

- name: Install clamav antivirus suite
  apt:
    name: '{{ pkg }}'
    state: latest
  with_items:
    - clamav
    - clamav-base
    - clamav-freshclam
    - clamdscan
    - clamsmtp
    - ipcalc
  loop_control:
    loop_var: pkg

- name: Set up the configuration file
  notify: Restart clamsmtpd
  template:
    src: clamsmtpd.conf
    dest: /etc/clamsmtpd.conf

- name: Get the remote locale
  tags: locale
  set_fact:
    lang: '{{ ansible_env.LANG | regex_replace("\..*", "") }}'

- name: Create the clamsmtp templates directory
  file:
    path: /etc/clamsmtp
    state: directory
    owner: clamsmtp
    group: clamsmtp
    mode: '0700'

- name: Copy the virus alert template
  template:
    src: '{{ item }}'
    dest: '/etc/clamsmtp/virus-alert-default.eml'
    owner: clamsmtp
    group: clamsmtp
    mode: '0600'
  with_first_found:
    - 'virus-alert-{{ lang }}.eml'
    - 'virus-alert-default.eml'

- name: Copy the virus alert script
  template:
    src: virus-alert.sh
    dest: /usr/local/bin/virus-alert.sh
    owner: clamsmtp
    group: clamsmtp
    mode: '0700'
