---
# These are the default values, you can copy and paste into your system.yml
# configuration file for customisation.


# Standard policies
policies:
  system:
    password: 'length=16 chars=ascii_letters,digits'
    passphrase: 'length=40'

# LDAP configuration
ldap:
  hostname: 'ldap.{{ network.domain }}'
  organization:
    domain: '{{ network.domain }}'
    base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  users:
    dn: 'ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  groups:
    dn: 'ou=groups, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  manager:
    uid: manager
    dn: 'cn=manager account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  readonly:
    uid: readonly
    dn: 'cn=readonly account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  admin:
    dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    desc: administrator account
  postmaster:
    uid: postmaster
    dn: 'cn=postmaster account, ou=users, dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    # See https://www.ietf.org/rfc/rfc2142.txt
    mailAliases:
      - 'abuse@{{ network.domain }}'
      - 'noc@{{ network.domain }}'
      - 'security@{{ network.domain }}'
      - 'mailer-daemon@{{ network.domain }}'
      - 'webmaster@{{ network.domain }}'
      - 'hostmaster@{{ network.domain }}'
      - 'admin@{{ network.domain }}'
      - 'root@{{ network.domain }}'

  # password params
  roPasswdParams: "{{ playbook_dir }}/../../backup/ldap/readonly.pwd {{ policies.system.password }}"
  managerPasswdParams: "{{ playbook_dir }}/../../backup/ldap/manager.pwd {{ policies.system.password }}"
  adminPasswdParams: "{{ playbook_dir }}/../../backup/ldap/admin.pwd {{ policies.system.password }}"
  postmasterPasswdParams: "{{ playbook_dir }}/../../backup/ldap/postmaster.pwd {{ policies.system.password }}"


# Encryption parameters
encryption:
  systemKeyParams: "{{ playbook_dir }}/../../backup/encryption/system-key.pwd {{ policies.system.passphrase }}"
  backupKeyParams: "{{ playbook_dir }}/../../backup/encryption/backup-key.pwd {{ policies.system.passphrase }}"

###############################################################################
# Email related default options
mail_default:
  max_attachment_size: 25   # In megabytes
  autoconfig: true          # Support Thunderbird automatic configuration
  autodiscover: false       # Support MS Outlook automatic configuration (uses https)
  quota:
    port: 30000             # port used by dovecot for the quota daemon
    default: 1G             # Maximum allowed mailbox size for your users.
                            # The safe maximum value will be automatically computed in a next version.
  discard_duplicates: false # Discard duplicates messages. It is safe, but has some side effects when you are
                            # sending a message to a mailing list. This is now disabled by default.
                            # The default timerange to search duplicated messages is one hour.
  #############################################################################
  antispam:                 # Check inbound and outbound emails for viruses
    port: 33000             # port to use for the antivirus daemon
    webui:                  # rspamd web interface
      active: true          # Activate or not
      allow:                # a list of IP address that can access the web interface
        - 192.168.0.0/16    # RFC1918 local networks
        - 172.16.0.0/12
        - 10.0.0.0/8
  #############################################################################
  antivirus:                # Check inbound and outbound emails for viruses
    port: 34000             # port to use for the antivirus daemon
    active: true            # or false
    action: drop            # Action to do when a virus is found in an email: bounce or drop
                            # be careful, bouncing external emails is a way to expose clamav usage
    send_warnings: false    # Send a warning email to - internal - users who are sending viruses
    quarantine: yes         # Place emails with a virus in quarantine, for further analysis
  #############################################################################
  impersonate:              # Activate dovecot "master" user feature, ideal for families and communities
    active: false           # https://wiki2.dovecot.org/Authentication/MasterUsers
    master: master          # master user name
    separator: '*'          # Separation char between master user / real user name. I personally use '/'
  #############################################################################
  import:                   # If you have users with "import" email active scripts, set this flag to true
    username: import        # The name of the user that import emails
    active: false           # A master user, with reduced rights will be created, to append miported emails
                            # in user's mailboxes.
  #############################################################################
  # Dovecot / solr FTS (Full Text search)
  fts:
    active: true
    langs:
      - id: fr
        name: French
      - id: en
        name: English
  #############################################################################
  advanced_features: false  # Use some advanced features that will need the latest version of dovecot
                            # from stretch-backports, like those below.
                            # like sending emails to an international addresses (e.g. andré@homebox.space)
  recipient_delimiter: '+'  # The characters you want to use to split email address from mailbox, i.e.:
                            # when receiving a message to john+lists@example.com, it should go directly to
                            # the 'lists' folder... I personally use '~'

###############################################################################
# Default password policies for users
passwords_default:
  min_length: 8
  max_age: 31536000        # 365 days max
  max_failure: 5
  expire_warning: 259200   # 3 days
  require_nonalpha: true
  # Keep track of the passwords you have used before
  # If you do not want, set this value to 0
  # Passwords are stored using salted SHA512, safe enough
  remember: 12
  # Password quality module
  # See: https://www.networkworld.com/article/3198444/linux/the-complexity-of-password-complexity.html
  quality:
    enforce: true
    params:
      - name: retry
        value: 5
      - name: minlen
        value: 8
      - name: minclass
        value: 3
      - name: maxrepeat
        value: 3
      - name: maxclassrepeat
        value: 4
      - name: lcredit
        value: 1
      - name: ucredit
        value: 1
      - name: ocredit
        value: 3
      - name: dcredit
        value: 1
      - name: difok
        value: 3

###############################################################################
# Default system settings
system_default:
  release: stretch
  login: true
  ssl: letsencrypt
  devel: false
  debug: false

###############################################################################
# Once the system is in place, it is possible to use 'limit' for the rule, instead of any.
# It is also possible to use fail2ban, which is installed anyway
firewall_default:
  ssh:
    from: any
    rule: allow

###############################################################################
# Extra security values
security_default:
  auto_update: true
  app_armor: true

###############################################################################
# Dictionaries to install in the system
dictionaries_default:
  - name: English
    id: en

###############################################################################
# Gandi automatic DNS update
# Your Gandi Key should be 24 characters long, e.g. zaNGbUVIvi1KbYb6PPMdiQLh
# update: Automatic update of your DNS server
# test: test mode: does not activate the DNS zone straight
# add_wildcard:  Create a wildcard entry to redirect all traffic to your box
dns_default:
  update: true
  test: true
  add_wildcard: true
  gandi:
    handle: JD123-GANDI
    key: zaNGbUVIvi1KbYb6PPMdiQLh

###############################################################################
# Install a static web site on www.yourdomain.com
# Still requests two certificates:
# One for for https://yourdomain.com/ and one for https://www.yourdomain.com
website_default:
  install: false

###############################################################################
# Install a webmail, or not...
webmail_default:
  install: true
  type: roundcube

###############################################################################
backup_default:
  install: false

###############################################################################
# Default list of development packages to install
# You can override it in your config/system.yml file
# they are installed when running the playbook dev-support,
# and removed when using dev-cleanup

devel_default:
  packages:
    - mc
    - telnet
    - dnsutils
    - whois
    - tmux
    - pfqueue
    - aptitude
    - man
    - less
    - vim
    - net-tools
    - file
    - swaks
    - curl
    - locate
    - colorized-logs
    - bash-completion
    - cyrus-clients
    - zsh
  root:
    shell: /bin/zsh


###############################################################################
# DKIM keys default parameters
dkim_default:
  key_size: 4096
  selector: main
  note: 'main DKIM key for the domain {{ network.domain }}'
  milter:
    port: 31000

###############################################################################
# DMARC keys default parameters
dmarc_default:
  milter:
    port: 32000

###############################################################################
# Jabber server
# The port numbers are not exposed externally, everything
# is behind nginx, in https.
# By default, the server is open to other servers (public flag to true).
# To restrict to only a few domains, set the flag to false, and
# enter the list of domains in the trust array
ejabberd_default:
  install: true
  allow_contrib_modules: false
  # Ban clients after too much authentication failures (1h after 10 attempts)
  fail2ban:
    active: true
    lifetime: 3600
    failures: 10
  # Server-to-server communication
  s2s:
    active: true
    use_starttls: required_trusted
    public: true
    trust:
      - jabber.org
  # https upload module
  http_upload:
    port: 5443
    secret_length: 40
    max_size: 104857600
    thumbnail: false
  # direct file transfer
  file_transfer:
    port: 7778
  # traffic shaper
  shaper:
    normal: 1000
    fast: 50000
    proxyrate: 10240 # file transfer proxy

###############################################################################
# Bind server defaults
bind_default:
  install: false
  forward:
    - 1.1.1.1
    - 8.8.8.8
    - 8.8.4.4
