# Host files for the homebox project, with fwknop SPA
# This is an example on how to use SPA / fwknop with Ansible.
# The arguments are detailed below.

all:
  hosts:
    homebox:
      ansible_host: homebox.example.home
      ansible_user: root
      ansible_port: 22
      # special parameters when using fwknop port knocking
      fwknop_src: 192.168.14.55   # or 'auto' when connecting to a remote host over internet.
      fwknop_config_name: main.example.home
      fwknop_dest: main.example.home
      fwknop_rc_file: /home/andre/.fwknop-example.home.rc
      fwknop_verbose: true
      fwknop_executable: '/usr/bin/fwknop'
      fwknop_extra_args: >-
          --no-save-args
          --no-home-dir
          -E /tmp/fwknop-example.home.run

# fwknop parameters:
# fwknop_src:
#   default: 'auto'
#   description: Default source IP address to use for fwknop
#   env: [{name: FWKNOP_SRC}]
#   ini:
#   - {key: fwknop_src, section: ssh_connection}
#   type: string
#   vars:
#     - name: fwknop_src
#       version_added: '2.7'
# fwknop_dest:
#   description: default destination address / domain to send SPA traffic
#   env: [{name: FWKNOP_DEST}]
#   ini:
#   - {key: fwknop_dest, section: ssh_connection}
#   type: string
#   vars:
#     - name: fwknop_dest
#       version_added: '2.7'
# fwknop_rc_file:
#   default: 'auto'
#   description: Configurlation file to read for fwknop
#   env: [{name: FWKNOP_RC_FILE}]
#   ini:
#   - {key: fwknop_rc_file, section: ssh_connection}
#   type: string
#   vars:
#     - name: fwknop_rc_file
#       version_added: '2.7'
# fwknop_verbose:
#   version_added: '2.5'
#   default: 'yes'
#   description: Use verbose output flags for fwknop
#   env: [{name: FWKNOP_VERBOSE}]
#   ini:
#   - {key: fwknop_verbose, section: ssh_connection}
#   type: bool
#   vars:
#     - name: fwknop_verbose
#       version_added: '2.7'
# fwknop_config_name:
#   version_added: '2.5'
#   description: Configuration name to use (-n)
#   env: [{name: FWKNOP_CONFIG_NAME}]
#   ini:
#   - {key: fwknop_config_name, section: ssh_connection}
#   type: string
#   vars:
#     - name: fwknop_config_name
#       version_added: '2.7'
# fwknop_executable:
#   version_added: '2.5'
#   default: '/usr/bin/fwknop'
#   description: path to the fwknop executable
#   env: [{name: FWKNOP_EXECUTABLE}]
#   ini:
#   - {key: fwknop_executable, section: ssh_connection}
#   type: string
#   vars:
#     - name: fwknop_executable
#       version_added: '2.7'
# fwknop_extra_args:
#   version_added: '2.5'
#   description: extra arguments for fwknop client
#   env: [{name: FWKNOP_EXTRA_ARGS}]
#   ini:
#   - {key: fwknop_extra_args, section: ssh_connection}
#   type: string
#   vars:
#     - name: fwknop_extra_args
#       version_added: '2.7'
