# Sample ini file for ansible

all:
  hosts:
    homebox:
      ansible_host: homebox.office.pm
      ansible_user: root
      ansible_port: 22
    cdbuilder:
      ansible_host: localhost
      ansible_user: root
      ansible_port: 22
