---

# Set up the autodiscover feature for Microsoft outlook
- hosts: homebox
  vars:
    certificate:
      type: autodiscover
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - autodiscover
    - certificates
