
# Install the borgbackup package
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    key:
      path: /root/.ssh/
      user: root
      comment: SSH key for backup
      name: backup
      passphrase: ~
  roles:
    - ssh-keygen
    - borg-backup
