---

# Crate the certificate for dovecot (POP3)
- hosts: homebox
  vars:
    certificate:
      type: pop3
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - certificates
