---
# Main playbook

- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - packages
    - system-prepare
    
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/accounts.yml
  roles:
    - certificates
    - accounts

# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/postfix.yml
  roles:
    - certificates
    - opendkim
    - postfix

# Update Gandi DNS, especially the DKIM record
- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - dns-gandi-update

# Install and configure dovecot
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/dovecot.yml
  roles:
    - certificates
    - dovecot

# Install a basic webmail
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/webmail.yml
  roles:
    - certificates
    - roundcube
    - autoconfig

