---
# Main playbook

- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - packages

- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/accounts.yml
  roles:
    - accounts


# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/postfix.yml
  roles:
    - certificates
    - dovecot
    - postfix

