---
# Main playbook

- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - packages

- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/accounts.yml
  roles:
    - accounts
    - certificates


# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/postfix.yml
  roles:
    - certificates
    - opendkim
    - postfix

# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/dovecot.yml
  roles:
    - certificates
    - dovecot

# Install a basic webmail
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/webmail.yml
  roles:
    - certificates
    - roundcube
