---
# Main playbook

- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - packages

- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/accounts.yml
  roles:
    - accounts
    - certificates


# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/postfix.yml
  roles:
    - opendkim
    - postfix
    - certificates

# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/dovecot.yml
  roles:
    - dovecot
    - certificates

# Install a basic webmail
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/webmail.yml
  roles:
    - roundcube
    - certificates

