# Install tools to import emails from other platforms

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  vars:
  roles:
    - import-emails
