# Create the accounts
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  vars:
    clean: False      # Do not delete the previous users if running again the script
    certificate:
      type: ldap
  roles:
    - certificates
    - ldap
