# Create the accounts
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  vars:
    clean: False      # Do not delete the previous users if running again the script
    certificate:
      type: ldap
  roles:
    - certificates
    - ldap
