---
## Main installation playbook

# Prepare the system
import_playbook:
- system-prepare.yml
- accounts.yml
- rspamd.yml
- opendmarc.yml
- cert-smtp.yml
- opendkim.yml
- postfix.yml
- dns-update.yml
- cert-pop3.yml
- cert-imap.yml
- dovecot.yml
- roundcube.yml
- autodiscover.yml
- autoconfig.yml
