---
## Main installation playbook

# Complete list of playbooks to run, in this order
- import_playbook: external-ip.yml
- import_playbook: system-prepare.yml
- import_playbook: ldap.yml
- import_playbook: homes.yml

# System protection: antispam
- import_playbook: rspamd.yml

# System protection: antivirus
- import_playbook: clamav.yml
  when: mail.antivirus.active

# Email server: MTA
- import_playbook: opendkim.yml
- import_playbook: opendmarc.yml
- import_playbook: cert-smtp.yml
- import_playbook: postfix.yml

# Create DNS entries (Only Gandi for now)
- import_playbook: dns-update.yml

# Mail delivery agent (dovecot)
- import_playbook: cert-pop3.yml
- import_playbook: cert-imap.yml
- import_playbook: dovecot.yml

# Install nginx as the default web server, if needed
- import_playbook: nginx.yml
  when: webmail.install or mail.autodiscover or mail.autoconfig or website.install

# Install the selected webmail
- import_playbook: roundcube.yml
  when: webmail.install and webmail.type == 'roundcube'

# Install ejabberd, with LDAP authentication
- import_playbook: ejabberd.yml
  when: ejabberd.install

# Install a simple but secure (https) web site skeleton
- import_playbook: website-simple.yml
  when: website.install

# Automatic configuration for email clients.
- import_playbook: autodiscover.yml
  when: mail.autodiscover
- import_playbook: autoconfig.yml
  when: mail.autoconfig

# Install the web frontend for the antispam system
- import_playbook: rspamd-web.yml
  when: mail.antispam.webui.active

# Backup script using borg-backup
- import_playbook: borgbackup.yml
  when: backup.install

# Add the old emails import scripts for each users
# Except when in development mode.
# It can alter the tests and is CPU intensive if you have
# defined a lot of accounts.
- import_playbook: import-accounts.yml
  when: mail.import.active and not system.devel
