---
## Main installation playbook

# Prepare the system
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  roles:
    - packages
    - system-prepare
    - ports-assign

# Create the accounts
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  vars:
    certificate:
      type: ldap
  roles:
    - certificates
    - accounts

# Add antispam filtering via rspamd
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  roles:
    - rspamd
    
# Install and configure opendmarc
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  roles:
    - opendmarc
    
# Install and configure postfix
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  vars:
    certificate:
      type: smtp
  roles:
    - certificates
    - opendkim
    - postfix

# Generate the records on Gandi DNS
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  roles:
    - dns-gandi-update

# Install and configure dovecot
- hosts: homebox
  vars:
    certificate:
      type: imap
  vars_files:
    - ../../config/system.yml
  roles:
    - certificates
    - dovecot

# Install a basic webmail (roundcube)
- hosts: homebox
  vars:
    certificate:
      type: webmail
  vars_files:
    - ../../config/system.yml
  roles:
    - certificates
    - roundcube
    - autoconfig

# Configure security, especially AppArmor
- hosts: homebox
  vars_files:
    - ../../config/system.yml
  roles:
    - security
