---
# Main playbook

- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - packages
    - system-prepare
    
- hosts: homebox
  vars_files:
    - variables/common.yml
  vars:
    certificate:
      cn: 'ldap.{{ network.domain }}'
      email: 'admin@{{ network.domain }}'
      readby: openldap
  roles:
    - certificates
    - accounts

# Add antispam filtering via rspamd
- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - rspamd
    
# Install and configure opendmarc
- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - opendmarc
    
# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
  vars:
    certificate:
      cn: 'smtp.{{ network.domain }}'
      email: 'admin@{{ network.domain }}'
      readby: postfix
  roles:
    - certificates
    - opendkim
    - postfix

# Update Gandi DNS, especially the DKIM record
- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - dns-gandi-update

# Install and configure dovecot
- hosts: homebox
  vars:
    certificate:
      cn: 'imap.{{ network.domain }}'
      email: 'admin@{{ network.domain }}'
      readby: dovecot
  vars_files:
    - variables/common.yml
  roles:
    - certificates
    - dovecot

# Install a basic webmail
- hosts: homebox
  vars:
    certificate:
      cn: 'webmail.{{ network.domain }}'
      email: 'admin@{{ network.domain }}'
      readby: www-data
  vars_files:
    - variables/common.yml
  roles:
    - certificates
    - roundcube
    - autoconfig

# Configure security
- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - security
