---

# Install a basic webmail (roundcube)
- hosts: homebox
  vars:
    certificate:
      type: webmail
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
    - '{{ playbook_dir }}/roles/roundcube/variables/main.yml'
  roles:
    - certificates
    - roundcube
