---
## Main installation playbook

# Basic system tests
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - tests-system-base
    - tests-ldap
    - tests-home
    - tests-rspamd
    - tests-opendmarc

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    certificate:
      type: smtp
  roles:
    - tests-certificate

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
    - '{{ playbook_dir }}/roles/opendkim/defaults/main.yml'
  roles:
    - ports-assign
    - tests-opendkim

