---
## Full tests playbook

# Basic system tests
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - tests-system-base
    - tests-ldap
    - tests-home
    - tests-rspamd
    - tests-opendmarc

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    certificate:
      type: smtp
  roles:
    - tests-certificate

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
    - '{{ playbook_dir }}/roles/opendkim/defaults/main.yml'
  roles:
    - ports-assign
    - tests-opendkim
    - tests-postfix

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    certificate:
      type: pop3
  roles:
    - tests-certificate

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    certificate:
      type: imap
  roles:
    - tests-certificate

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
    - '{{ playbook_dir }}/roles/dovecot/defaults/main.yml'
  roles:
    - tests-dovecot

# Web sites tests
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - tests-roundcube
    - tests-autoconfig
    - tests-autodiscover

