---
## Self diagnostic / basic unit tests suite to run before commiting
##

# Install development support packages needed to run the tests
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - dev-support

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - load-defaults
    - tests-system-base
    - tests-ldap
    - tests-home
    - tests-rspamd
    - tests-opendmarc

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    certificate:
      type: smtp
  roles:
    - tests-certificate

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
    - '{{ playbook_dir }}/roles/opendkim/defaults/main.yml'
  roles:
    - ports-assign
    - tests-opendkim

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - ports-assign
    - tests-postfix

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    certificate:
      type: pop3
  roles:
    - tests-certificate

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
  vars:
    certificate:
      type: imap
  roles:
    - tests-certificate

- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
    - '{{ playbook_dir }}/roles/dovecot/defaults/main.yml'
  roles:
    - tests-dovecot

# Web sites tests
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - tests-roundcube

# Autoconfig / Autodiscover tests (when using it)
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - tests-autoconfig
    - tests-autodiscover

# Test if the antivirus is bouncing emails
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - tests-clamav
