---
## Main installation playbook

# Basic system tests
- hosts: homebox
  vars_files:
    - '{{ playbook_dir }}/../../config/system.yml'
    - '{{ playbook_dir }}/defaults/main.yml'
  roles:
    - tests-system-base
    - tests-ldap

