---

- name: Update packages cache
  become: true
  become_method: su
  tags: apt
  apt:
    update_cache: true
    
- name: install the required packages to build the ISO image
  become: true
  become_method: su
  tags: apt
  apt:
    name: '{{ pkg }}'
    state: installed
  with_items:
    - simple-cdd
    - tar
    - xorriso
  loop_control:
    loop_var: pkg

