---
# Webmail configuration (roundcube, http ATM)
webmail:
  url: webmail2.rodier.me
  secure_port: 443

# Network related
network:
  smtp: smtp2.rodier.me
  imap: imap2.rodier.me
  hostname: mail2.rodier.me
  domain: rodier.me

# Certificate details
certificate:
  email: andre@rodier.me

mail:
  admin:
    email: andre@rodier.me
    user: andre
