# LDAP configuration
ldap:
  hostname: 'ldap.{{ network.domain }}'
  organization:
    domain: '{{ network.domain }}'
    base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  users:
    dn: 'ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  groups:
    dn: 'ou=groups,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  manager:
    uid: manager
  admin:
    dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    desc: administrator account

# DKIM keys parameters
dkim:
  key_size: 2048
  selector: main
  note: 'main DKIM key for the domain {{ network.domain }}'
  milter:
    port: '{{ milter_dkim_port }}'

# Postfix blacklists to use
# See https://en.wikipedia.org/wiki/Comparison_of_DNS_blacklists
dns_blacklists:
  - zen.spamhaus.org
  - b.barracudacentral.org

antispam:
  milter:
    name: rspamd
    port: '{{ milter_antispam_port }}'
