---

- name: Get the passwords generated in the accounts tasks
  tags: roundcube
  set_fact:
    roPasswdParams: "../../backup/ldap/readonly.pwd length=16 chars=ascii_letters,digits"

- name: Install roundcube webmail
  tags: roundcube
  apt:
    name: "{{ pkg }}"
    state: installed
  with_items:
    - postgresql
    - roundcube-pgsql
    - roundcube-core
    - roundcube-plugins
    - roundcube-plugins-extra
    - roundcube
    - imapproxy
    - php-fpm
    - php-ldap
    - php-net-sieve
    - php-net-ldap2
    - php-net-ldap3       # For LDAP address book
    - nginx
    - makepasswd
    - haveged             # speed up password generation
  loop_control:
    loop_var: pkg

################################################################################
# At this point, the certificates should have been created already #############
# in order to have SSL and TLS encryption activated.                           #
- name: Allow slapd and nslcd daemons to access the certificate directories
  tags: ldap,ssl
  notify: Restart nginx
  when: system.ssl == 'letsencrypt'
  vars:
    details:
      - [ /etc/letsencrypt/archive, /etc/letsencrypt/live ]
      - [ www-data ]
  acl:
    path: '{{ item[0] }}'
    entity: '{{ item[1] }}'
    etype: user
    permissions: rx
    state: present
  with_nested: '{{ details }}'

#                                                                              #
# End of TLS / SSL Configuration ###############################################

- name: Disable nginx default site
  tags: roundcube
  notify: Restart nginx
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent
    force: yes

- name: Create the webmail site
  tags: roundcube
  notify: Restart nginx
  template:
    src: webmail-site.tpl
    dest: /etc/nginx/sites-available/roundcube.conf
    owner: root
    group: root
    mode: 0644

- name: Configure the IMAP proxy
  tags: roundcube
  notify: Restart IMAP proxy
  template:
    src: imapproxy.conf
    dest: /etc/imapproxy.conf
    owner: root
    group: root
    mode: 0644

- name: Copy roundcube configuration
  tags: roundcube
  notify: Restart nginx
  template:
    src: webmail-site.tpl
    dest: /etc/nginx/sites-available/roundcube.conf
    owner: root
    group: root
    mode: 0644

- name: Create a session key for roundcube
  tags: roundcube
  notify: Restart nginx
  shell: makepasswd --chars=24
  register: makepasswd

- name: Copy roundcube configuration
  tags: roundcube
  notify: Restart nginx
  template:
    src: '{{ file }}'
    dest: '/etc/roundcube/{{ file }}'
    owner: root
    group: root
    mode: 0644 
  with_items:
    - config.inc.php
  loop_control:
    loop_var: file

- name: Copy roundcube plugins configuration
  tags: roundcube
  notify: Restart nginx
  template:
    src: '{{ file }}.php'
    dest: '/etc/roundcube/plugins/{{ file }}/config.inc.php'
    owner: root
    group: www-data
    mode: 0640
  with_items:
    - password
    - new_user_identity
  loop_control:
    loop_var: file

- name: Enable nginx site
  tags: roundcube
  notify: Restart nginx
  file:
    src: '/etc/nginx/sites-available/roundcube.conf'
    dest: '/etc/nginx/sites-enabled/roundcube.conf'
    state: link

# There is bugs in the name of the symbolic links on Debian
# https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=roundcube-plugins-extra;dist=unstable 
- name: Make sure the plugins are correctly named
  tags: roundcube
  notify: Restart nginx
  command: mv '/var/lib/roundcube/plugins/{{ folder.old }}' '/var/lib/roundcube/plugins/{{ folder.new }}'
  args:
    creates: '/var/lib/roundcube/plugins/{{ folder.new }}'
  with_items:
    - old: keyboard-shortcuts
      new: keyboard_shortcuts
    - old: thunderbird-labels
      new: thunderbird_labels
  loop_control:
    loop_var: folder

- name: Configure the firewall for default access
  tags: security
  ufw:
    rule: allow
    proto: tcp
    src: any
    port: '{{ rule.port }}'
    comment: '{{ rule.comment }}'
  with_items:
    - comment: Allow http access, but it will be redirected to https directly
      port: 80
    - comment: Allow https access to the webmail
      port: 443
  loop_control:
    loop_var: rule

- name: Install nginx AppArmor profile
  when: security.app_armor
  tags: security, apparmor
  template:
    src: apparmor.d/usr.sbin.nginx
    dest: /etc/apparmor.d/usr.sbin.nginx
    
