---

- name: Install opendmarc related packages
  tags: opendmarc
  apt:
    name: '{{ pkg }}'
    state: latest
  with_items:
    - opendmarc
  loop_control:
    loop_var: pkg

- name: Comment all active socket for DMARC
  tags: opendmarc
  replace:
    path: /etc/default/opendmarc
    regexp: '^SOCKET=(.*)'
    replace: '#SOCKET=\1'

- name: Add tcp interface on localhost
  tags: opendmarc
  lineinfile:
    path: /etc/default/opendmarc
    line: 'SOCKET=inet:{{ dmarc.milter.port }}@localhost'


