---

- name: If the certificates have been generated before, copy them on the remote server
  tags: cert
  synchronize:
    src: ../../../backup/certificates/
    dest: /etc
    owner: no
    group: no
    perms: yes
    rsync_opts:
      - '--no-motd'
      - '--checksum'
      - '--exclude=readme.md'

- name: Check if nginx has been already installed
  tags: cert
  register: stat_result
  stat:
    path: /usr/sbin/nginx

- name: Stop the nginx server if installed
  when: stat_result.stat["exists"] == True
  tags: cert
  service:
    name: nginx
    state: stopped

# The certbot package need to be installed
- name: Create the certificate
  tags: cert
  when: system.ssl == 'letsencrypt'
  command: >-
    /usr/bin/certbot certonly
    --non-interactive
    --standalone
    --domain "{{ certificate.cn }}"
    --email "{{ certificate.email }}"
    --agree-tos
  args:
    creates: "/etc/letsencrypt/live/{{ certificate.cn }}/cert.pem"
    
- name: Restart the nginx server if installed
  when: stat_result.stat["exists"] == True
  tags: cert
  service:
    name: nginx
    state: started

- name: Backup the certificates on your local machine
  tags: cert
  synchronize:
    mode: pull
    src: /etc/letsencrypt
    dest: ../../../backup/certificates/
    perms: yes
