---

- name: Check if nginx has been already installed
  tags: cert
  register: stat_result
  stat:
    path: /usr/sbin/nginx

- name: Stop the nginx server if installed
  when: stat_result.stat["exists"] == True
  tags: cert
  service:
    name: nginx
    state: stopped

# The certbot package need to be installed
- name: Create the certificate
  tags: cert
  when: system.ssl == 'letsencrypt'
  command: >-
    /usr/bin/certbot certonly
    --non-interactive
    --standalone
    --domain "{{ certificate.cn }}"
    --email "{{ certificate.email }}"
    --agree-tos
  args:
    creates: "/etc/'letsencrypt'/live/{{ certificate.cn }}/cert.pem"
    
- name: Restart the nginx server if installed
  when: stat_result.stat["exists"] == True
  tags: cert
  service:
    name: nginx
    state: started

    
