---

# Initialise the packages repository to a standard,
# including backports, contrib and non-free software
- name: Initialise default repositories
  tags: apt
  template:
    src: sources.list
    dest: /etc/apt/sources.list
                
- name: Update packages repositories
  tags: apt
  register: packages_cache
  apt:
    update_cache: yes

- name: Upgrade the distribution
  tags: apt
  when: packages_cache.changed
  apt:
    upgrade: yes

