---

- name: Install a DNS server
  apt:
    name: bind9
    state: present

- name: Copy the configuration template
  notify: Restart bind
  vars:
    serial: "{{ lookup('pipe', 'date +%s') }}"
  template:
    src: '{{ file.src }}'
    dest: '/etc/bind/{{ file.dest | default(file.src) }}'
  with_items:
    - src: named.conf.options
    - src: named.conf.local
    - src: forward-head
      dest: 'forward.d/00-head.bind'
    - src: reverse-domain
      dest: 'reverse.{{ network.domain }}'
  loop_control:
    loop_var: file

- name: Build the final bind configuration
  assemble:
    src: '/etc/bind/forward.d'
    dest: '/etc/bind/forward.{{ network.domain }}'
    delimiter: '\n;---'
    regexp: '^.*\.bind$'

- name: Allow queries to the DNS server from outside
  ufw:
    from_ip: any
    to_ip: any
    proto: udp
    to_port: 53
    comment: 'Allow DNS queries from outside'
    rule: allow
