---

- name: Install isync package
  apt:
    name: '{{ pkg }}'
    state: latest
  with_items:
    - isync
  loop_control:
    loop_var: pkg

- name: Create the emails migration and imports folders
  file:
    path: '/home/users/{{ user.uid }}/mails/import'
    owner: '{{ user.uid }}'
    group: users
    state: directory
    mode: 0700
  with_items:
    - '{{ users }}'
  loop_control:
    loop_var: user

- name: Build a template for each account and each user
  include_tasks: roles/migrate-emails/tasks/isync-template.yml
  with_items:
    - '{{ users }}'
  loop_control:
    loop_var: user
