---

- name: Install nginx
  apt:
    name: "{{ pkg }}"
    state: present
  with_items:
    - nginx
  loop_control:
    loop_var: pkg

################################################################################
# At this point, the certificates should have been created already #############
# in order to have SSL and TLS encryption activated.                           #
- name: Allow the web server to access certificates
  tags: ssl
  notify: Restart nginx
  vars:
    details:
      - [ /etc/letsencrypt, /etc/letsencrypt/archive, /etc/letsencrypt/live ]
      - [ www-data ]
  acl:
    path: '{{ item[0] }}'
    entity: '{{ item[1] }}'
    etype: user
    permissions: rx
    state: present
  with_nested: '{{ details }}'

#                                                                              #
# End of TLS / SSL Configuration ###############################################

- name: Disable nginx default site
  notify: Restart nginx
  file:
    path: '/etc/nginx/sites-enabled/default'
    state: absent
    force: yes

- name: Configure the firewall for default access
  tags: ufw, security
  ufw:
    rule: allow
    proto: tcp
    src: any
    port: '{{ rule.port }}'
    comment: '{{ rule.comment }}'
  with_items:
    - comment: Allow http/https access
      port: 80,443
  loop_control:
    loop_var: rule


# Security improvements =======================================================

- name: Generate a strong Diffie Hellman
  tags: security
  openssl_dhparam:
    path: /etc/nginx/dhparams.pem
    size: 2048
    mode: 0600
    owner: root
    group: root

- name: Use the generated DH for SSL
  tags: security
  lineinfile:
    path: /etc/nginx/nginx.conf
    insertafter: '^(\t|\s)+ssl_.*'
    line: "\tssl_dhparam /etc/nginx/dhparams.pem;"

- name: Disable weak ciphers
  tags: security
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^(\t|\s)ssl_protocols TLSv1 TLSv1.1 TLSv1.2.*'
    line: "\tssl_protocols TLSv1.2;"

# AppArmor configuration ======================================================

- name: Install nginx AppArmor profile
  when: security.app_armor
  tags: security, apparmor
  template:
    src: 'apparmor.d/usr.sbin.nginx'
    dest: '/etc/apparmor.d/usr.sbin.nginx'
    force: no

- name: Activate AppArmor profiles
  when: security.app_armor
  tags: roundcube, security, apparmor
  command: 'aa-enforce usr.sbin.nginx'
  notify: Restart AppArmor service
