---

- name: Install nginx packages
  apt:
    name: "{{ pkg }}"
    state: installed
    default_release: jessie-backports
  with_items:
    - nginx-common
    - nginx-full
    - nginx
  loop_control:
        loop_var: pkg
    
