
- name: Restart dovecot
  tags: dovecot
  notify: Compile global sieve scripts
  service:
    name: dovecot
    state: restarted

- name: Compile global sieve scripts
  tags: dovecot
  command: '/usr/bin/sievec /etc/dovecot/sieve/{{ file }}'
  with_items:
    - report-spam.sieve
    - report-ham.sieve
    - before-global.sieve
    - append-checks.sieve
  loop_control:
    loop_var: file


- name: Restart AppArmor service
  tags: dovecot
  service:
    name: apparmor
    state: restarted
