---

# This create random ports for the services in the system, ensuring that they don't overlap each other
# The port numbers are often shared between postfix and dovecot

# Until these bugs fixed...
# https://github.com/ansible/ansible/issues/15249
# https://github.com/pallets/jinja/pull/708
# There is apparently a fix in Ansible 2.7
#
# - name: Assign ports for various services
#   tags: facts
#   when: system.devel == false
#   set_fact:
#     mails_quota_port: "{{ 30000 + ( 900 | random ) | int }}"
#     milter_dkim_port: "{{ 31000 + ( 900 | random ) | int }}"
#     milter_dmarc_port: "{{ 32000 + ( 900 | random ) | int }}"
#     milter_antispam_port: "{{ 33000 + ( 900 | random ) | int }}"
#     filter_antivirus_port: "{{ 34000 + ( 900 | random ) | int }}"
#
# # In development, use constant ports, so we can redeploy postfix / dovecot
# # without haveing to redeploy milters
# - name: Assign ports for various services
#   when: system.devel == true
#   tags: facts
#   set_fact:
#     mails_quota_port: 30000
#     milter_dkim_port: 31000
#     milter_dmarc_port: 32000
#     milter_antispam_port: 33000
#     filter_antivirus_port: 34000

- name: Assign ports for various services
  tags: facts
  set_fact:
    mails_quota_port: 30000
    milter_dkim_port: 31000
    milter_dmarc_port: 32000
    milter_antispam_port: 33000
    filter_antivirus_port: 34000
