---
# Main playbook

- hosts: homebox
  vars_files:
    - variables.yml
  roles:
    # - packages
    # - accounts
    - certificates
    - dovecot
    - postgresql
    - nginx
    - roundcube
    - security
