---
# Main playbook

- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - packages

- hosts: homebox
  vars_files:
    - variables/accounts.yml
  roles:
    - accounts

# Install and configure postfix
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/postfix.yml
  roles:
    - certificates
    - postfix

# Install and configure dovecot
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/dovecot.yml
  roles:
    - certificates
    - dovecot

# Configure nginx web server, especially the HTTPS
- hosts: homebox
  vars_files:
    - variables/webmail.yml
  roles:
    - certificates

# Configure services
- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - postgresql

# Install the webmail, and nginx configuration
- hosts: homebox
  vars_files:
    - variables/common.yml
    - variables/webmail.yml
  roles:
    - nginx
    - roundcube


# Configure the firewall and various security options    
- hosts: homebox
  vars_files:
    - variables/common.yml
  roles:
    - security

###
