webmail:
  url: 'webmail.{{ network.domain }}'
  secure_port: 443
  title: 'Roundcube Webmail ({{ ldap.organization.domain }})'
  enigma: no
  plugins:
    - password
    - archive
    - jqueryui
    - dkimstatus
    - markasjunk
    - newmail_notifier
    - autologon
    - subscriptions_option
    - emoticons
    - new_user_identity
    - managesieve
    - contextmenu
    - keyboard_shortcuts

# Available plugins:
# - hide_blockquote
# - thunderbird_labels
# - enigma
# - zipdownload
# - new_user_dialog
# - additional_message_headers
# - acl
# - database_attachments
# - debug_logger
# - filesystem_attachments
# - help
# - hide_blockquote
# - http_authentication
# - jqueryui
# - show_additional_headers
# - squirrelmail_usercopy
# - userinfo
# - vcard_attachments
# - virtuser_file
# - virtuser_query
