# LDAP configuration
ldap:
  hostname: 'ldap.{{ network.domain }}'
  organization:
    domain: '{{ network.domain }}'
    base: 'dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  users:
    dn: 'ou=users,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  groups:
    dn: 'ou=groups,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
  manager:
    uid: manager
  admin:
    dn: 'cn=admin,dc={{ network.domain | regex_replace("\.", ",dc=") }}'
    desc: administrator account

roundcube:
  url: 'webmail.{{ network.domain }}'
  title: 'Roundcube Webmail ({{ ldap.organization.domain }})'
  enigma: no
  max_attachment_size: 25   # In megabytes
  plugins:
    - password
    - archive
    - jqueryui
    - markasjunk
    - newmail_notifier
    - autologon
    - subscriptions_option
    - emoticons
    - new_user_identity
    - managesieve
    - contextmenu

# Available plugins:
# - keyboard_shortcuts
# - dkimstatus
# - hide_blockquote
# - thunderbird_labels
# - enigma
# - zipdownload
# - new_user_dialog
# - additional_message_headers
# - acl
# - database_attachments
# - debug_logger
# - filesystem_attachments
# - help
# - hide_blockquote
# - http_authentication
# - show_additional_headers
# - squirrelmail_usercopy
# - userinfo
# - vcard_attachments
# - virtuser_file
# - virtuser_query
