roundcube:
  url: 'webmail.{{ network.domain }}'
  title: 'Roundcube Webmail ({{ ldap.organization.domain }})'
  enigma: no
  max_attachment_size: 25   # In megabytes
  plugins:
    - password
    - archive
    - jqueryui
    - markasjunk
    - newmail_notifier
    - autologon
    - subscriptions_option
    - emoticons
    - new_user_identity
    - managesieve
    - contextmenu
    - thunderbird_labels

# Available plugins:
# - keyboard_shortcuts
# - dkimstatus
# - hide_blockquote
# - enigma
# - zipdownload
# - new_user_dialog
# - additional_message_headers
# - acl
# - database_attachments
# - debug_logger
# - filesystem_attachments
# - help
# - hide_blockquote
# - http_authentication
# - show_additional_headers
# - squirrelmail_usercopy
# - userinfo
# - vcard_attachments
# - virtuser_file
# - virtuser_query
