---

- name: Create the group home folders if necessary
  tags: accounts
  file:
    path: /home/users
    owner: root
    group: users
    state: directory

- name: Also add these folders into the skeletonf, for new users
  tags: accounts
  file:
    path: '{{ dir }}'
    owner: root
    group: root
    state: directory
    mode: 0700
    recurse: true
  with_items:
    - /etc/skel/mails/maildir
    - /etc/skel/mails/sieve
  loop_control:
    loop_var: dir

- name: Create home directory for users on first login
  tags: ldap
  when: system.login == true
  lineinfile:
    dest: /etc/pam.d/common-account
    line: 'session    required    pam_mkhomedir.so skel=/etc/skel/ umask=0022'


