---
################################################################################
# Merge user options with default options
- name: Use default mail settings
  when: mail is not defined
  set_fact:
    mail: mail_default

- name: Combine default and user defined mail settings
  when: mail is defined
  set_fact:
    mail: '{{ mail_default | combine(mail) }}'

- name: Display merged mail settings
  when: mail is defined and system.debug
  debug:
    var: mail

################################################################################
- name: Install packages needed for dovecot fts
  apt:
    update_cache: yes
    cache_valid_time: 86400
    name: '{{ pkg }}'
    state: latest
  with_items:
    - tomcat8
    - solr-tomcat
    - dovecot-solr
    - poppler-utils  # PDF text extraction
    - catdoc         # .doc, .xls and .ppt extract
  loop_control:
    loop_var: pkg

- name: Copy decode2text script
  copy:
    src: decode2text.sh
    dest: /usr/local/bin/decode2text.sh
    mode: 0755

- name: Copy solr schema
  notify: Restart tomcat
  template:
    src: solr-schema.xml
    dest: /etc/solr/conf/schema.xml
